# H2 Properties
spring:
  datasource:
    url: jdbc:h2:mem:user
    password: password
    username: sa
    driver-class-name: org.h2.Driver
    
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
        
    
zuul:
  routes:
    component-processing:
      path: /component-processing/**
      service-id: component-processing-microservice
      strip-prefix: false
     
    payment-module:
      path: /payment/**
      service-id: Payment-service 
      strip-prefix: false
      
    PackagingAndDelivery-service:
      path: /packaging-and-delivery/**
      service-id: PackagingAndDelivery-service
      strip-prefix: false  
      
      